Repository NewShiftStudio/gour-store-front, pull requests merged in 2022-09, with the labels that each got.

#102 Bugs
  assets/images/game/background.svg
  assets/images/game/button-small.svg
  components/Auth/Signup/CitySelect/CitySelect.tsx
  components/Auth/Signup/Credentials/Credentials.styles.ts
  components/Auth/Signup/Credentials/Credentials.tsx
  components/Auth/Signup/ReferralCode/validation.ts
  components/Game/Alarm/Alarm.tsx
  components/Game/Main/Main.stories.tsx
  components/Game/Main/Main.styles.ts
  components/Game/Main/Main.tsx
  components/Game/RulesModal/RulesModal.tsx
  components/HookForm/HFSelect.tsx
  components/Order/Form/Form.styles.ts
  components/Order/Form/Form.tsx
  components/UI/Modal/Modal.styles.ts
  components/UI/Modal/Modal.tsx
  components/UI/Select/Select.tsx
  hooks/useTranslation.ts
  i18n/en.json
  i18n/ru.json
  layouts/Game/Game.tsx
  layouts/Shop/Shop.tsx
  pages/auth/signup.tsx
  pages/game/index.tsx
Labels: bug, feat

#110 QA-881: Footer email
  constants/contacts.ts
  package-lock.json
  types/entities/ErrorWithMessage.ts
  utils/errorUtil.ts
Labels: bug

#106 QA-879: Delivery info block, order cheque
  components/Order/Card/Card.styles.ts
  components/Order/Card/Card.tsx
  components/UI/Info/Block/Block.tsx
  pages/_document.tsx
  pages/basket/Basket.styles.ts
  pages/basket/index.tsx
Labels: bug

#105 QA-899: Main address change
  components/PA/Profiles/Form/Form.i18n.json
  components/PA/Profiles/Form/Form.tsx
  constants/routes.ts
  layouts/PA/PA.tsx
  pages/personal-area/addresses/index.tsx
  pages/personal-area/credentials/index.tsx
  store/api/currentUserApi.ts
Labels: bug

#118 feat: change auth for email code
  components/Auth/Signup/Credentials/Credentials.i18n.json
  components/Auth/Signup/Credentials/Credentials.stories.tsx
  components/Auth/Signup/Credentials/Credentials.tsx
  components/Auth/Signup/Credentials/validation.ts
  components/UI/ImageSlider/ImageSlider.tsx
  next.config.js
  pages/auth/signup.tsx
  types/dto/signup-form.dto.ts
  types/dto/signup.dto.ts
Labels: feat
