Repository NewShiftStudio/gour-store-front, pull requests merged in 2022-10, with the labels that each got.

#132 Feat: почтовые коды подтверждения
  .example.env
  components/Auth/Card/Card.tsx
  components/Auth/Signin/Credentials/Credentials.tsx
  components/Auth/Signin/PassRecovery/PassRecovery.i18n.json
  components/Auth/Signin/PassRecovery/PassRecovery.stories.tsx
  components/Auth/Signin/PassRecovery/PassRecovery.styles.ts
  components/Auth/Signin/PassRecovery/PassRecovery.tsx
  components/Auth/Signin/PassRecovery/validation.ts
  components/Auth/Signup/Credentials/Credentials.i18n.json
  components/Auth/Signup/Credentials/Credentials.stories.tsx
  components/Auth/Signup/Credentials/Credentials.styles.ts
  components/Auth/Signup/Credentials/Credentials.tsx
  components/Auth/Signup/Credentials/validation.ts
  components/HookForm/HFTextField.tsx
  components/PA/Credentials/AvatarEditor/AvatarEditor.tsx
  components/PA/Credentials/Editor/Editor.stories.tsx
  components/PA/Credentials/Editor/Editor.tsx
  components/PA/Credentials/EmailChangeModal/EmailChangeModal.i18n.json
  components/PA/Credentials/EmailChangeModal/EmailChangeModal.styles.ts
  components/PA/Credentials/EmailChangeModal/EmailChangeModal.tsx
  components/PA/Credentials/EmailChangeModal/validation.ts
  components/PA/Credentials/PasswordChangeModal/PasswordChangeModal.i18n.json
  components/PA/Credentials/PasswordChangeModal/PasswordChangeModal.tsx
  components/PA/Credentials/PhoneChangeModal/PhoneChangeModal.tsx
  components/PA/Credentials/PhoneChangeModal/validation.ts
  constants/routes.ts
  pages/auth/signin.tsx
  pages/auth/signup.tsx
  pages/index.tsx
  pages/personal-area/credentials/index.tsx
  store/api/authApi.ts
  store/api/currentUserApi.ts
  types/dto/check-code.dto.ts
  types/dto/password-recovery.dto.ts
  types/dto/profile/change-email.dto.ts
  types/dto/profile/change-phone.dto.ts
  types/dto/profile/send-code.dto.ts
  types/dto/profile/update-user.dto.ts
  types/dto/signin.dto.ts
  types/dto/signup-form.dto.ts
  utils/errorUtil.ts
Labels: feat

#136 feat: поле пароля с иконкой глаза
  components/Auth/Signin/PassRecovery/PassRecovery.tsx
  components/Auth/Signup/Credentials/Credentials.tsx
  components/HookForm/HFPassField.tsx
  components/PA/Credentials/PasswordChangeModal/PasswordChangeModal.tsx
Labels: feat

#137 fix: 🐛 валидация полей авторизации, очистка ошибок при вводе
  components/Auth/Signin/Credentials/Credentials.tsx
  components/HookForm/HFTextField.tsx
Labels: bug

#140 hotfix: email code check
  components/Auth/Signin/PassRecovery/PassRecovery.tsx
  components/Auth/Signup/Credentials/Credentials.tsx
  components/Discounts/Group/Group.tsx
  components/Header/Header.tsx
  components/PA/Credentials/EmailChangeModal/EmailChangeModal.tsx
  pages/auth/signin.tsx
  pages/auth/signup.tsx
  pages/personal-area/credentials/index.tsx
  pages/personal-area/discounts/index.tsx
  store/api/categoryApi.ts
Labels: hotfix

#142 fix: скрытый копирайт
  layouts/Game/Game.tsx
  layouts/Shop/Shop.tsx
  pages/personal-area/discounts/index.tsx
Labels: bug

#146 Изменил положение количества товара в карточке заказа
  components/Order/Card/Card.styles.ts
  components/Order/Card/Card.tsx
Labels: bug

#150 Hotfix: Баг стилей при билде. Pre-push
  package.json
  pages/Page.styles.tsx
  pages/[key].tsx
  pages/personal-area/discounts/index.tsx
Labels: bug

#143 fix: отображение Олега, стран и продуктов
  assets/icons/countries/CountrySvgSelector.tsx
  assets/icons/countries/russia.svg
  assets/icons/example/example-icon.svg
  assets/icons/flags/rus.svg
  assets/icons/flags/uk.svg
  assets/icons/mobile/countries/russia.svg
  assets/icons/products/Group 91.svg
  assets/icons/products/ProductsSvgSelector.tsx
  assets/icons/signup/credentials.svg
  assets/icons/signup/favorites.svg
  assets/icons/signup/table.svg
  assets/images/default.svg
  assets/images/example/example-image.png
  assets/images/no-avatar.png
  assets/images/signup/city.svg
  assets/images/signup/credentials.svg
  assets/images/signup/favorites.svg
  assets/images/signup/greetings.svg
  assets/images/signup/referral-codes.svg
  assets/no-image.png
  components/Auth/Card/Card.tsx
  components/Auth/Signup/CitySelect/CitySelect.tsx
  components/Auth/Signup/FavoriteInfo/FavoriteInfo.i18n.json
  components/Auth/Signup/FavoriteInfo/FavoriteInfo.module.scss
  components/Auth/Signup/FavoriteInfo/FavoriteInfo.stories.tsx
  components/Auth/Signup/FavoriteInfo/FavoriteInfo.styles.ts
  components/Auth/Signup/FavoriteInfo/FavoriteInfo.tsx
  components/Auth/Signup/Layout/Layout.styles.ts
  components/Auth/Signup/Layout/Layout.tsx
  components/Cart/Card/Card.tsx
  components/PA/Credentials/AvatarEditor/AvatarEditor.tsx
  components/PA/Main/CredentialsCard/CredentialsCard.tsx
  components/Product/Card/Card.stories.tsx
  components/Product/Card/Card.tsx
  components/Product/Filter/Multiselect/Multiselect.tsx
  components/UI/ImageSlider/ImageSlider.tsx
  constants/countries.ts
  constants/favorites.ts
  pages/auth/signup.tsx
  types/entities/IOption.ts
  utils/countryUtil.ts
Labels: bug, style

#141 bug: изменение почты после отправки кода
  components/Auth/Signin/PassRecovery/PassRecovery.tsx
  components/Auth/Signup/Credentials/Credentials.tsx
  components/HookForm/HFPassField/HFPassField.styles.ts
  components/HookForm/HFPassField/HFPassField.tsx
  components/HookForm/HFSendField/HFSendField.styles.ts
  components/HookForm/HFSendField/HFSendField.tsx
  components/PA/Credentials/EmailChangeModal/EmailChangeModal.tsx
  components/PA/Credentials/PasswordChangeModal/PasswordChangeModal.tsx
  components/PA/Main/CredentialsCard/CredentialsCard.tsx
  pages/_app.tsx
  pages/_document.tsx
  public/favicon.ico
Labels: bug, feat, style

#157 feat: 🎸 Изменил метод рендера описания продукта
  pages/products/[id].tsx
Labels: feat

#156 Feat: Возможность заказа продуктов по граммам
  .storybook/preview.js
  components/CardSlider/CardSlider.module.scss
  components/CardSlider/CardSlider.styles.ts
  components/CardSlider/CardSlider.tsx
  components/Navigation/NavigationProvider.tsx
  components/Product/Actions/Actions.i18n.json
  components/Product/Actions/Actions.styles.ts
  components/Product/Actions/Actions.tsx
  components/Product/Card/Card.stories.tsx
  components/Product/Card/Card.styles.ts
  components/Product/Card/Card.tsx
  components/Product/Card/Cart.tsx
  components/Product/Card/Cart/Cart.styles.ts
  components/Product/Card/Cart/Cart.tsx
  components/Product/Card/Docket.tsx
  components/Product/Card/Docket/Docket.styles.ts
  components/Product/Card/Docket/Docket.tsx
  components/Product/Card/GramSelect/GramSelect.styles.ts
  components/Product/Card/GramSelect/GramSelect.tsx
  components/Product/Card/Rate/Rate.styles.ts
  components/Product/Card/Rate/Rate.tsx
  components/Product/Catalog/Catalog.tsx
  components/Product/Information/Information.styles.ts
  components/Product/Information/Information.tsx
  components/UI/Select/Select.tsx
  constants/gramList.ts
  constants/routes.ts
  pages/products/Product.styles.ts
  pages/products/[id].tsx
  store/api/warehouseApi.ts
  themes.ts
  types/dto/warehouse/get-stock.dto.ts
  types/entities/IProduct.ts
  types/entities/IWarehouseStock.ts
  utils/catalogUtil.ts
Labels: feat

#167 feat: уведомления о начале игры, кнопка логаута в игре
  components/Game/Main/Main.tsx
  components/Header/Header.tsx
  components/Product/Card/GramSelect/GramSelect.styles.ts
  components/Product/Card/GramSelect/GramSelect.tsx
  components/UI/Modal/Modal.i18n.json
  components/UI/Modal/Modal.styles.ts
  components/UI/Modal/Modal.tsx
Labels: feat

#160 fix: 🐛 перенос строки для описания продуктов
  components/Product/Actions/Actions.tsx
  components/Product/Card/Card.tsx
  components/Product/Card/GramSelect/GramSelect.tsx
  pages/products/Product.styles.ts
Labels: fix

#163 feat: отправка граммовок при создании заказа
  pages/order/index.tsx
  types/dto/order/product.dto.ts
Labels: feat

#161 fix: 🐛 chapter links
  components/Header/Header.styles.ts
  components/Header/Header.tsx
  components/Mobile/Menu/Menu.tsx
  components/PA/Main/AddressCard/AddressCard.tsx
  components/PA/Main/CredentialsCard/CredentialsCard.tsx
  components/PA/Main/DiscountsCard/DiscountsCard.tsx
  components/PA/Main/OrdersCard/OrdersCard.tsx
  components/PA/Menu/Menu.stories.tsx
  components/PA/Menu/Menu.styles.ts
  components/PA/Menu/Menu.tsx
  components/UI/Info/Card/Card.styles.ts
  components/UI/Info/Card/Card.tsx
  components/UI/List/List.tsx
  layouts/Game/Game.tsx
  layouts/PA/PA.tsx
  layouts/Shop/Shop.tsx
  pages/personal-area/index.tsx
Labels: fix

#172 fix: валидация номера телефона в личном кабинете
  components/Auth/Signin/PassRecovery/PassRecovery.tsx
  components/Auth/Signup/Credentials/Credentials.tsx
  components/PA/Credentials/Editor/Editor.i18n.json
  components/PA/Credentials/Editor/validation.ts
  components/PA/Credentials/EmailChangeModal/EmailChangeModal.tsx
  components/PageContent/PageContent.tsx
  hooks/useStopwatch.ts
  layouts/Game/Game.tsx
  layouts/Shop/Shop.tsx
Labels: fix

#169 fix: 🐛 отображение страниц с информацией для неавторизованного
  layouts/Shop/Shop.styles.ts
  layouts/Shop/Shop.tsx
  pages/[key].tsx
Labels: fix

#166 fix: 🐛 main address change
  components/PA/Profiles/Form/Form.tsx
  components/PA/Profiles/Item/Item.tsx
  pages/personal-area/addresses/index.tsx
Labels: fix

#177 fix: 🐛 скидка товара
  components/Product/Actions/Actions.tsx
  components/Product/Card/Card.tsx
  pages/products/[id].tsx
Labels: fix

#173 fix: валидация почты на кириллицу
  components/Auth/Signin/Credentials/Credentials.i18n.json
  components/Auth/Signin/Credentials/validation.ts
  components/Auth/Signin/PassRecovery/validation.ts
  components/Auth/Signup/Credentials/validation.ts
  components/PA/Credentials/EmailChangeModal/EmailChangeModal.i18n.json
  components/PA/Credentials/EmailChangeModal/validation.ts
  constants/regex.ts
Labels: fix

#176 fix: 🐛 элемент для отображения текста
  components/UI/Typography/Typography.tsx
Labels: fix

#178 feat: 🎸 функциональность для пополнения чизкоинов в layouts
  components/Cart/Card/Card.tsx
  components/Cart/Info/Info.tsx
  components/Cheesecoins/AddModal/AddModal.tsx
  components/Cheesecoins/BuyModal/BuyModal.tsx
  components/Header/Header.tsx
  components/Mobile/Menu/Menu.tsx
  components/Navigation/NavigationContext.ts
  components/Navigation/NavigationProvider.tsx
  components/Orders/Card/Card.stories.tsx
  components/Orders/Card/Card.tsx
  components/Orders/Card/CardProduct.tsx
  constants/routes.ts
  layouts/Game/Game.tsx
  layouts/PA/PA.tsx
  layouts/Shop/Shop.tsx
  pages/basket/index.tsx
  pages/personal-area/orders/ordersHelper.ts
  types/entities/IProduct.ts
Labels: feat

#164 feat: 🎸 жизни в игре, уведомления о статусе игры
  assets/icons/heart.svg
  components/Game/Main/Core.ts
  components/Game/Main/Main.stories.tsx
  components/Game/Main/Main.styles.ts
  components/Game/Main/Main.tsx
  components/Product/Actions/Actions.tsx
  components/Promotion/Card/Card.tsx
  constants/routes.ts
  pages/game/index.tsx
  pages/index.tsx
  store/api/currentUserApi.ts
  types/entities/ICurrentUser.ts
Labels: feat

#165 feat: Система жизней игры
  assets/icons/heart.svg
  components/Game/Main/Core.ts
  components/Game/Main/Main.stories.tsx
  components/Game/Main/Main.styles.ts
  components/Game/Main/Main.tsx
  components/Header/Header.tsx
  components/Order/Card/Card.tsx
  components/Product/Actions/Actions.tsx
  components/Product/Card/GramSelect/GramSelect.styles.ts
  components/Product/Card/GramSelect/GramSelect.tsx
  components/Promotion/Card/Card.tsx
  components/UI/Modal/Modal.i18n.json
  components/UI/Modal/Modal.styles.ts
  components/UI/Modal/Modal.tsx
  constants/routes.ts
  pages/game/index.tsx
  pages/index.tsx
  store/api/currentUserApi.ts
  types/entities/ICurrentUser.ts
Labels: feat

#182 fix: 🐛 запрос на уменьшение игровой жизни
  store/api/currentUserApi.ts
Labels: fix

#190 fix: 🐛 отображение продуктов в акции
  components/Product/Catalog/Catalog.tsx
  components/Product/Filter/List/List.tsx
  components/Product/Filter/Modal/Modal.tsx
  pages/promotions/[id].tsx
Labels: fix
